name: ngs-pipeline
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - snakemake=8.*
  - fastp=0.23.*
  - fastqc=0.12.*
  - multiqc=1.21.*
  - bwa=0.7.*
  - samtools=1.19.*
  - gatk4=4.5.*
  - bcftools=1.19.*
  - tabix
  - ensembl-vep=111.*
  - pysam=0.22.*
  - pandas
  - matplotlib
  - pip
  - pip:
      - snakemake-wrapper-utils
